west_teams = [
    "LAL",
    "LAC",
    "DEN",
    "OKC",
    "UTA",
    "HOU",
    "DAL",
    "MEM",
    "POR",
    "SAS",
    "PHO",
    "SAC",
    "GSW",
    "MIN",
    "NOP",
]

east_teams = [
    "MIL",
    "TOR",
    "BOS",
    "MIA",
    "IND",
    "PHI",
    "ORL",
    "NJN",
    "WAS",
    "CHA",
    "CHI",
    "NYK",
    "DET",
    "ATL",
    "CLE",
]

positions = {
    "Point Guard": "PG",
    "Shooting Guard": "SG",
    "Small Forward": "SF",
    "Power Forward": "PF",
    "Center": "C",
}


per_game = {
    "pos": "pos",
    "age": "age",
    "tm": "team_id",
    "g": "g",
    "gs": "gs",
    "mp": "mp_per_g",
    "fg": "fg_per_g",
    "fga": "fga_per_g",
    "fg%": "fg_pct",
    "3p": "fg3_per_g",
    "3pa": "fg3a_per_g",
    "3p%": "fg3_pct",
    "2p": "fg2_per_g",
    "2pa": "fg2a_per_g",
    "2p%": "fg2_pct",
    "efg%": "efg_pct",
    "ft": "ft_per_g",
    "fta": "fta_per_g",
    "ft%": "ft_pct",
    "orb": "orb_per_g",
    "drb": "drb_per_g",
    "trb": "trb_per_g",
    "ast": "ast_per_g",
    "stl": "stl_per_g",
    "blk": "blk_per_g",
    "tov": "tov_per_g",
    "pf": "pf_per_g",
    "pts": "pts_per_g",
}

min_stats = {
    "pmpos": "pos",
    "pmage": "age",
    "pmtm": "team_id",
    "pmg": "g",
    "pmgs": "gs",
    "pmmp": "mp_per_mp",
    "pmfg": "fg_per_mp",
    "pmfga": "fga_per_mp",
    "pmfg%": "fg_pct",
    "pm3p": "fg3_per_mp",
    "pm3pa": "fg3a_per_mp",
    "pm3p%": "fg3_pct",
    "pm2p": "fg2_per_mp",
    "pm2pa": "fg2a_per_mp",
    "pm2p%": "fg2_pct",
    "pmefg%": "efg_pct",
    "pmft": "ft_per_mp",
    "pmfta": "fta_per_mp",
    "pmft%": "ft_pct",
    "pmorb": "orb_per_mp",
    "pmdrb": "drb_per_mp",
    "pmtrb": "trb_per_mp",
    "pmast": "ast_per_mp",
    "pmstl": "stl_per_mp",
    "pmblk": "blk_per_mp",
    "pmtov": "tov_per_mp",
    "pmpf": "pf_per_mp",
    "pmpts": "pts_per_mp",
}

poss_stats = {
    "ppos": "pos",
    "page": "age",
    "ptm": "team_id",
    "pg": "g",
    "pgs": "gs",
    "pmp": "mp_per_poss",
    "pfg": "fg_per_poss",
    "pfga": "fga_per_poss",
    "pfg%": "fg_pct",
    "p3p": "fg3_per_poss",
    "p3pa": "fg3a_per_poss",
    "p3p%": "fg3_pct",
    "p2p": "fg2_per_poss",
    "p2pa": "fg2a_per_poss",
    "p2p%": "fg2_pct",
    "pefg%": "efg_pct",
    "pft": "ft_per_poss",
    "pfta": "fta_per_poss",
    "pft%": "ft_pct",
    "porb": "orb_per_poss",
    "pdrb": "drb_per_poss",
    "ptrb": "trb_per_poss",
    "past": "ast_per_poss",
    "pstl": "stl_per_poss",
    "pblk": "blk_per_poss",
    "ptov": "tov_per_poss",
    "ppf": "pf_per_poss",
    "ppts": "pts_per_poss",
    "ortg": "off_rtg",
    "drtg": "def_rtg",
}


advanced_stats = {
    "per": "per",
    "ts%": "ts_pct",
    "3par": "fg3a_per_fga_pct",
    "ftr": "fta_per_fga_pct",
    "orb%": "orb_pct",
    "drb%": "brd_pct",
    "trb%": "trb_pct",
    "ast%": "ast_pct",
    "stl%": "stl_pct",
    "blk%": "blk_pct",
    "tov%": "tov_pct",
    "usg%": "usg_pct",
    "ows": "ows",
    "dws": "dws",
    "ws": "ws",
    "ws/48": "ws_per_48",
    "obpm": "obpm",
    "dbpm": "dbpm",
    "bpm": "bpm",
    "vorp": "vorp",
}


nba_teams = {
    "Atlanta Hawks": "atl",
    "Brooklyn Nets": "njn",
    "Boston Celtics": "bos",
    "Charlotte Hornets": "cha",
    "Chicago Bulls": "chi",
    "Cleveland Cavaliers": "cle",
    "Dallas Mavericks": "dal",
    "Detroit Pistons": "det",
    "Golden State Warriors": "gsw",
    "Houston Rockets": "hou",
    "Indiana Pacers": "ind",
    "Los Angeles Clippers": "lac",
    "Los Angeles Lakers": "lal",
    "Memphis Grizzlies": "mem",
    "Miami Heat": "mia",
    "Milwaukee Bucks": "mil",
    "Minnesota Timberwolves": "min",
    "New Orleans Pelicans": "noh",
    "Orlando Magic": "orl",
    "Philadelphia 76ers": "phi",
    "Phoenix Suns": "pho",
    "Portland Trail Blazers": "por",
    "Sacramento Kings": "sac",
    "San Antonio Spurs": "sas",
    "Toronto Raptors": "tor",
    "Utah Jazz": "uta",
    "Washington Wizards": "was",
    "Oklahoma City Thunder": "okc",
    "Seattle Supersonics": "okc",
    "Denver Nuggets": "den",
    "New York Knicks": "nyk",
}

player_nicknames = {
    "kd": "Kevin Durant",
    "kat": "Karl-Anthony Towns",
    "boogie": "Demarcus Cousins",
    "uncle drew": "Kyrie Irving",
    "king": "Lebron James",
    "ai": "Allen Iverson",
    "mamba": "Kobe Bryant",
    "unicorn": "Kristaps Porzingis",
    "kareem": "Kareem Abdul-Jabbar",
    "ice trae": "Trae Young",
    "beard": "James Harden",
    "bald mamba": "Alex Caruso",
    "fox": "de'aaron fox",
    "giannis": "Giannis Antetokounmpo",
}

stats_needed = [
    "Season",
    "Age",
    "Tm",
    "Pos",
    "G",
    "PER",
    "TS%",
    "3PAr",
    "FTr",
    "USG%",
    "WS",
    "BPM",
    "VORP",
    "season",
    "age",
    "team_id",
    "pos",
    "g",
    "per",
    "ts_pct",
    "fg3a_per_fga_pct",
    "fta_per_fga_pct",
    "usg_pct",
    "ws",
    "bpm",
    "vorp",
]


stats_not_needed = [
    "Lg",
    "2P",
    "2PA",
    "2P%",
    "DRB",
    "PF",
    "GS",
    "3PA",
    "ORB",
    "FG",
    "FGA",
    "3P",
    "eFG%",
    "FT",
    "FTA",
    "TOV",
    "Pos",
    "tov_per_g",
    "fga_per_g",
    "fg3_per_g",
    "pos",
    "efg_pct",
    "ft_per_g",
    "fta_per_g",
    "gs",
    "fg3a_per_g",
    "fg2_per_g",
    "fg2a_per_g",
    "fg2_pct",
    "orb_per_g",
    "drb_per_g",
    "pf_per_g",
    "lg_id",
    "fg_per_g",
]


stat_full_name = {
    "mp": "minutes",
    "fg": "field goals",
    "fga": "field goals",
    "fg_pct": "fg%",
    "fg3": "3-pointers",
    "fg3a": "3-pointers",
    "fg3_pct": "3p%",
    "fg2": "2-pointers",
    "fg2a": "2-pointers",
    "fg2_pct": "2p%",
    "efg_pct": "efg%",
    "ft": "free throws",
    "fta": "free throws",
    "ft_pct": "ft%",
    "orb": "offensive rebounds",
    "drb": "defensive rebounds",
    "trb": "total rebounds",
    "ast": "assists",
    "stl": "steals",
    "blk": "blocks",
    "tov": "turn-overs",
    "pf": "personal fouls",
    "pts": "points",
}
